# Generated by Django 4.1.7 on 2023-04-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_rename_petrol_type_ad_color_remove_ad_car_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='body_type',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='color',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='cylinder',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='engine_capacity',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='feul_type',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='location',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='make',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='mileage',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='model',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='ownership_status',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='price',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='transmission',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='trim',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='vin',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='year',
        ),
        migrations.AddField(
            model_name='ad',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
